# Generated by Django 5.0.6 on 2024-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_generatedimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="user",
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
